create or replace TABLE SUPPLIER (
	S_SUPPKEY NUMBER(38,0),
	S_NAME VARCHAR(25),
	S_ADDRESS VARCHAR(40),
	S_NATIONKEY NUMBER(38,0),
	S_PHONE VARCHAR(15),
	S_ACCTBAL NUMBER(12,2),
	S_COMMENT VARCHAR(101)
);